#!/usr/bin/env bash

set -o errexit
set -o pipefail

compliance_csv="$1"
bulletin_csv="$2"
combined_csv="$3"

compliance_csv_name=$(basename "$compliance_csv")
compliance_csv_name="${compliance_csv_name%.*}"

bulletin_csv_name=$(basename "$bulletin_csv")
bulletin_csv_name="${bulletin_csv_name%.*}"

csvsql \
    --no-inference \
    --query \
    "SELECT \
        c.\`PACKAGE SERIAL NUMBER\` as \`Package S/N\`, \
        CASE WHEN c.\`BULLETIN STATUS\` = 'In Work' THEN 'X' ELSE '' END AS \`In Work\`, \
        CASE WHEN c.\`BULLETIN STATUS\` = 'Completed' THEN 'X' ELSE '' END AS \`Complete\`, \
        c.\`BULLETIN COMMENTS\` as \`Comments\`, \
        c.\`PACKAGE NAME\` as \`Unit ID\`, \
        CASE WHEN c.\`BULLETIN STATUS\` = 'Completed' THEN c.\`BULLETIN DATE\` ELSE '' END AS \`Completed Date\`, \
        '' AS \`Index\`, \
        '' AS \`Document Type\`, \
        c.\`BULLETIN NUMBER\` AS \`Number\`, \
        b.\`ISSUED\` AS \`Issued\`, \
        b.\`REVISED\` AS \`Revised\`, \
        b.\`PRODUCT\` AS \`Product\`, \
        b.\`MODEL\` AS \`Model(s)\`, \
        b.\`SUBJECT\` AS \`Subject\`, \
        b.\`TYPE OF CHANGE\` AS \`Type of Change\`, \
        b.\`RECOMMENDED COMPLIANCE\` AS \`Recommended Compliance\` \
    FROM '$compliance_csv_name' c LEFT JOIN '$bulletin_csv_name' b \
    ON c.\`BULLETIN NUMBER\` = b.\`NUMBER\`" \
    $compliance_csv $bulletin_csv \
    > $combined_csv