#!/usr/bin/env php
<?php

// This takes a directory of PDF files, and extracts the relevant data, and outputs a CSV file

require __DIR__ . '/vendor/autoload.php';

$service_bulletin_directory = $argv[1];

if (!is_dir($service_bulletin_directory) OR !is_readable($service_bulletin_directory)) {
    echo "The path parameter is not a directory, or you do not have read permissions on the directory.";
}

$service_bulletin_directory = realpath($argv[1]);
$mime_type_parser = new \finfo(FILEINFO_MIME_TYPE);
$parser = new \Smalot\PdfParser\Parser();

$pdf_contents = [];
foreach (new \DirectoryIterator($service_bulletin_directory) as $service_bulletin_file) {
    
    if ($service_bulletin_file->isDot()) continue;

    if ($service_bulletin_file->getType() != 'file'
        OR $service_bulletin_file->getExtension() != 'pdf'
        OR $mime_type_parser->file($service_bulletin_file->getPathname()) != 'application/pdf') {
        echo "Skipping '{$service_bulletin_file->getFilename()}', not a PDF file.";
        echo "\n";
        continue;
    }

    $pdf = $parser->parseFile($service_bulletin_file->getPathname());
    $first_page = $pdf->getPages()[0];
    $first_page_text = $first_page->getText();

    var_dump($first_page_text);

}